// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace Rocket_IX
{
public static class GPGSIds
{
        public const string achievement_whats_this = "CgkIqf6GxowcEAIQDQ"; // <GPGSID>
        public const string achievement_subliminal_score = "CgkIqf6GxowcEAIQBQ"; // <GPGSID>
        public const string achievement_long_shot = "CgkIqf6GxowcEAIQDw"; // <GPGSID>
        public const string achievement_super_machine = "CgkIqf6GxowcEAIQDA"; // <GPGSID>
        public const string achievement_sugar_cube = "CgkIqf6GxowcEAIQBw"; // <GPGSID>
        public const string achievement_its_over_9000 = "CgkIqf6GxowcEAIQBA"; // <GPGSID>
        public const string achievement_almost_invincible = "CgkIqf6GxowcEAIQEA"; // <GPGSID>
        public const string achievement_getting_hot = "CgkIqf6GxowcEAIQDg"; // <GPGSID>
        public const string leaderboard_ranking = "CgkIqf6GxowcEAIQEg"; // <GPGSID> atualizado
        public const string achievement_another_color = "CgkIqf6GxowcEAIQAQ"; // <GPGSID>
        public const string achievement_collector_1 = "CgkIqf6GxowcEAIQCA"; // <GPGSID>
        public const string achievement_collector_2 = "CgkIqf6GxowcEAIQCQ"; // <GPGSID>
        public const string achievement_collector_3 = "CgkIqf6GxowcEAIQCg"; // <GPGSID>
        public const string achievement_collector_4 = "CgkIqf6GxowcEAIQCw"; // <GPGSID>
        public const string achievement_break_to_coffee = "CgkIqf6GxowcEAIQAw"; // <GPGSID>
        public const string achievement_i_am_rich = "CgkIqf6GxowcEAIQAg"; // <GPGSID>
        public const string achievement_nap_time = "CgkIqf6GxowcEAIQBg"; // <GPGSID>

}
}
